# 2023 Benjamin-Del 

# 
name: Generate and Deploy to GH Pages
run-name: Generate and Deploy to GH Pages
on: 
  # Run the workflow on push
  push:
  # Allow the workflow to be manually triggered
  workflow_dispatch:
jobs:
  # Build job
  build:
    # This job runs on the latest version of ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4
      # Setup the pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      # Run the (Custom) SSR script
      # Add the a flag to signify it is run by a GH Action.
      - name: Generate HTML
        run: node app.js -a ${{github.actor}}
      # Upload the artifact to the repo
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with: 
          path: ./
          retention-days: 1
  # Deployment job
  deploy:
    # Make sure the API token has the required scopes
    permissions:
      contents: read
      pages: write
      id-token: write 
    # Setup GH Pages  
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    # This job runs on the latest version of ubuntu
    runs-on: ubuntu-latest
    # This job runs after the build job
    needs: build
    # Deploy to GH Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
